### ISSUE TITLE
Label text change doesn't clear space

### ISSUE THREAD

**Issue by CalvinWalzel** [PhonicUK/CLRCLI#1]
Hey,

first of all thanks a lot for this library. I think it's amazing and has a lot of potential.

Now to my problem: If you have a label with a string and change the text of the label at runtime to a string that is shorter than the one before, the library does not clear the old string properly. A screenshot of the result is attached.

The text in the screenshot should only show "Item 0". I hope it's clear what I mean :)
![screen shot 2015-05-19 at 09 35 32](https://cloud.githubusercontent.com/assets/6446452/7697709/6eab9d04-fe0a-11e4-80c8-69718e2fe1ca.png)

**Comment by PhonicUK** [comment]
Got it. The workaround until its fixed is to change the string to empty spaces the same length as the original string, then change it to the desired one (which is what the actual fix will do)

**Comment by CalvinWalzel** [comment]
I've opened a pull request with a fix for this.
